api_keys:
- key: automation-key
  name: Automation
  permissions: read-write
- key: monitoring-key
  name: Monitoring
  permissions: read-only
pam:
  allow_root: false
  enabled: false
  groups:
    admin_group: openmux_admin
    read_group: openmux_read
    write_group: openmux_write
  service_name: login
users:
- is_admin: true
  password_hash: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
  username: admin
- is_admin: false
  password_hash: a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e
  username: user1
- is_admin: false
  password_hash: 628a7476ada25574e51158f5e9cec7a6b0a3356c93466ec78a768be9b6a394e1
  username: viewer
